services:
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    container_name: server
    build: ./server
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/simple_api
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple_api
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
